export { default as LogIn } from './LogIn'
export { default as Register } from './Register'
export { default as Home } from './Home'
export { default as Profile } from './Profile'
export { default as PostForm } from './PostForm'
